RohanNagar/thunder

application/pom.xml, application/src/main/java/com/sanction/thunder/ThunderApplication.java, application/src/main/java/com/sanction/thunder/ThunderConfiguration.java, application/src/main/java/com/sanction/thunder/authentication/Key.java, application/src/main/java/com/sanction/thunder/authentication/ThunderAuthenticator.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, config.yaml, pom.xml
=> Added authentication to thunder

README.md, application/src/main/java/com/sanction/thunder/ThunderApplication.java, application/src/main/java/com/sanction/thunder/ThunderComponent.java, application/src/main/java/com/sanction/thunder/ThunderConfiguration.java, application/src/main/java/com/sanction/thunder/ThunderModule.java, application/src/main/java/com/sanction/thunder/authentication/Key.java, application/src/main/java/com/sanction/thunder/authentication/ThunderAuthenticator.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/test/java/com/sanction/thunder/authentication/ThunderAuthenticatorTest.java, application/src/test/java/com/sanction/thunder/dao/PilotUsersDaoTest.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, pom.xml
There are a lot of things left incomplete, I just want you to see the general structure so far.
=> Authentication Update for Dropwizard 0.9.2

client/src/main/java/com/sanction/thunder/ThunderClient.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java
Changed client to reflect changes in application
=> Client Update

api/src/main/java/com/sanction/thunder/models/PilotUser.java, api/src/test/java/com/sanction/thunder/models/PilotUserTest.java, api/src/test/resources/fixtures/pilot_user.json, application/src/test/java/com/sanction/thunder/dao/PilotUsersDaoTest.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java, scripts/user_details.json
=> Remove Dropbox access token from PilotUser

.travis.yml, application/src/main/java/com/sanction/thunder/dao/PilotUsersDao.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/test/java/com/sanction/thunder/dao/PilotUsersDaoTest.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, client/src/main/java/com/sanction/thunder/ThunderClient.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java, scripts/tester.py, scripts/thunder_requests/methods.py, scripts/thunder_requests/update_user.py
Addresses #17.
This is not technically an API-breaking change, since the new query param is optional, but we should be careful when deploying a new version of Thunder to check for something breaking in Lightning or Pilot.
Lightning will have to make changes when it upgrades to a new version of Thunder, eventually.
=> Support changing email

api/pom.xml, api/src/main/java/com/sanction/thunder/models/PilotUser.java, application/pom.xml, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, client/pom.xml, client/src/main/java/com/sanction/thunder/ThunderBuilder.java, client/src/main/java/com/sanction/thunder/ThunderClient.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java, pom.xml
Most of the changes are test related because the email address "email" was hard-coded in each test case. Since that email is invalid, that would cause test cases to fail with the validation check.
I now use a single class variable to hold the email address used for testing, and reference that variable in all the tests.
Also, the validation is fairly loose, it won't catch everything possible but it will at least catch the basic invalid emails.
=> Validate email addresses

api/src/main/java/com/sanction/thunder/models/Email.java, api/src/main/java/com/sanction/thunder/models/PilotUser.java, api/src/test/java/com/sanction/thunder/models/EmailTest.java, api/src/test/java/com/sanction/thunder/models/PilotUserTest.java, api/src/test/resources/fixtures/email.json, api/src/test/resources/fixtures/pilot_user.json, application/src/main/java/com/sanction/thunder/dao/PilotUsersDao.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/main/java/com/sanction/thunder/resources/VerificationResource.java, application/src/test/java/com/sanction/thunder/dao/PilotUsersDaoTest.java, application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java, application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java
- Added /verify endpoint to validate an email
- Added ability to create a 32 byte random number for validating emails
- Appropriate unit tests
=> Added Email Verification

api/src/test/java/com/sanction/thunder/models/EmailTest.java, application/src/main/java/com/sanction/thunder/ThunderApplication.java, application/src/main/java/com/sanction/thunder/ThunderComponent.java, application/src/main/java/com/sanction/thunder/dao/DatabaseError.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/main/java/com/sanction/thunder/resources/VerificationResource.java, application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
- Remove duplicate `buildResponseForDatabaseError`
- Remove unused imports
- Actually register `VerificationResource` to Jersey
- Small cleanup
=> Cleanup and fixes

README.md, application/src/main/java/com/sanction/thunder/dao/PilotUsersDao.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/main/java/com/sanction/thunder/resources/VerificationResource.java, application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java, client/src/main/java/com/sanction/thunder/ThunderBuilder.java, client/src/main/java/com/sanction/thunder/ThunderClient.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java, scripts/tester.py, scripts/thunder_requests/methods.py, scripts/user_details.json
- Improve Python test script to call the `/verify` endpoint
- Fix a few bugs with email verification
- Add a few more unit tests for email verification database exceptions
- Add `verifyUser()` method to `ThunderClient`
=> Fix email verification bugs

README.md, pom.xml
- Combine DynamoDB and SES dependency versions so they are using the same version.
- Update README (Python scripts -> Node.js scripts, and Pulling in Client Library using JitPack)
=> Combine AWS dependency versions

.travis.yml, config/test-config.yaml, scripts/package.json, scripts/run-integration-tests.sh, scripts/src/test-runner.js
=> Add integration test bash script and run tests on Travis

README.md, client/pom.xml, client/src/main/java/com/sanction/thunder/ThunderBuilder.java, client/src/main/java/com/sanction/thunder/ThunderClient.java, client/src/test/java/com/sanction/thunder/ThunderClientTest.java, pom.xml
Addresses #47.
This is a breaking change in the client.
=> Upgrade Retrofit to v2.x

.travis.yml, README.md, scripts/src/aws-client.js, scripts/src/test-runner.js, scripts/tools/bootstrap.sh, scripts/tools/integration-tests.sh, scripts/tools/run-local-dependencies.js, scripts/tools/start-local-dependencies.js
- Adds a script to set up the machine for Thunder development: `scripts/tools/bootstrap.sh`
- Adds a script to start running local dependencies (DynamoDB and SES) easily: `scripts/tools/run-local-dependencies.js`
- Updates `README.md` to better explain how to get started running locally
- Other extra cleanup
This should make setting up a new machine for Thunder development way easier!
=> Bootstrap Script and Running Locally

.travis.yml, scripts/.eslintrc.yml, scripts/package-lock.json, scripts/package.json, scripts/src/aws-client.js, scripts/src/run-thunder-command.js, scripts/src/test-runner.js, scripts/src/thunder-client.js, scripts/tools/run-local-dependencies.js
This PR adds JS linting to ensure that all JS files follow a specific code style.
- Adds `eslint` dependency to run the linting.
- Adds the linting step to the Travis build.
- Adds a configuration file for linting based on the Google style guide.
- Fixes all existing linting issues so the build should pass.
=> Introduce ESLint for JS code style

.gitlab-ci.yml, .travis.yml, README.md, scripts/README.md, scripts/aws/dynamo-table.yaml, scripts/tools/bootstrap.sh, scripts/tools/integration-tests.sh
- Bootstrap script improvements. Addresses part of #128.
- Add `shellcheck` to Travis builds to verify `.sh` files are correct.
- DynamoDB CloudFormation template. Address part of #25.
- Remove some build steps from GitLab build that don't make sense. The GitLab build will only be responsible for building and pushing the Docker image.
Still todo:
Missing to be addressed in a later PR:
- Manual installs
=> Bootstrap Script Improvements and DynamoDB Template

api/src/main/java/com/sanction/thunder/models/Email.java, api/src/main/java/com/sanction/thunder/models/ResponseType.java, api/src/main/java/com/sanction/thunder/models/User.java, application/src/main/java/com/sanction/thunder/ThunderApplication.java, application/src/main/java/com/sanction/thunder/ThunderComponent.java, application/src/main/java/com/sanction/thunder/ThunderConfiguration.java, application/src/main/java/com/sanction/thunder/ThunderModule.java, application/src/main/java/com/sanction/thunder/authentication/Key.java, application/src/main/java/com/sanction/thunder/authentication/ThunderAuthenticator.java, application/src/main/java/com/sanction/thunder/dao/DaoModule.java, application/src/main/java/com/sanction/thunder/dao/DatabaseError.java, application/src/main/java/com/sanction/thunder/dao/DatabaseException.java, application/src/main/java/com/sanction/thunder/dao/UsersDao.java, application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbConfiguration.java, application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbHealthCheck.java, application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbModule.java, application/src/main/java/com/sanction/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java, application/src/main/java/com/sanction/thunder/email/EmailException.java, application/src/main/java/com/sanction/thunder/email/EmailModule.java, application/src/main/java/com/sanction/thunder/email/EmailService.java, application/src/main/java/com/sanction/thunder/resources/UserResource.java, application/src/main/java/com/sanction/thunder/resources/VerificationResource.java, application/src/main/java/com/sanction/thunder/util/EmailUtilities.java, application/src/main/java/com/sanction/thunder/validation/PropertyValidationRule.java, application/src/main/java/com/sanction/thunder/validation/PropertyValidator.java, application/src/test/java/com/sanction/thunder/authentication/ThunderAuthenticatorTest.java, client/src/main/java/com/sanction/thunder/ThunderBuilder.java, client/src/main/java/com/sanction/thunder/ThunderClient.java
- Addresses #136. Class-level Javadocs!
- Remove unused `throws` in the `ThunderAuthenticator`
- More explicit `null` checking in constructors
- Cleanup
=> Class Level Javadoc

.travis.yml, README.md, pom.xml
Move to Codecov (more support)
None
=> Use Codecov instead of Coveralls

.gitlab-ci.yml, config/docker-config.yaml, docker-compose.yml, scripts/lib/aws-client.js, scripts/lib/test-cases.js, scripts/tools/test-runner.js
Closes #206.
- Uses `docker-compose` to start Thunder, Local Dynamo, and Local SES
- Adds options to the integration tests to not start local dependencies and for running with docker-in-docker
- Runs the integration tests against the built Docker image in the GitLab CI build
None
=> Run integration tests against Docker image

application/src/main/java/com/sanction/thunder/resources/VerificationResource.java, application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
This addresses issue #224 
1. No documentation changes are required
=> Send email password match bug

application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java
Fixes #245.
Now when updating the email of a user, check to see if a user with the new email already exists first or not.
None
=> Fix accidental deletion bug

application/src/main/java/com/sanctionco/thunder/ThunderConfiguration.java, application/src/test/resources/fixtures/configuration/thunder-config-disabled-email.yaml, application/src/test/resources/fixtures/configuration/thunder-config.yaml, config/cloud-dev-config.yaml, config/docker-config.yaml, config/local-dev-config-disabled-email.yaml, config/local-dev-config.yaml, config/local-dev-properties-config.yaml, config/prod-config.yaml, config/test-config.yaml, scripts/kubernetes/thunder-config.yaml
This will allow us to more easily add new database providers without causing a breaking change in the future.
1. https://github.com/RohanNagar/thunder/wiki/Configuration-Options (Already done)
=> Change configuration option name from dynamo to database

application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, scripts/package-lock.json, scripts/tests/general/tests.yaml, scripts/tests/test-runner.js
Closes #297. Adds a new endpoint that will reset the verification status of a user.
Docs for endpoints don't exist yet so I can't update those. I will add this endpoint to the new endpoints documentation that is coming soon.
=> Feature: Reset Verification Status

application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/java/com/sanctionco/thunder/validation/RequestValidator.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, application/src/test/java/com/sanctionco/thunder/validation/RequestValidatorTest.java, scripts/tests/disabled-email/tests.yaml, scripts/tests/general/tests.yaml
Part of #232.
- Use `RequestValidator` in `VerificationResource`
- Move logic to update a user's email in `DynamoDbUsersDao` to a separate method to improve readability and maintainability
- Use consistent response messages
=> Small cleanup tasks

docs/manual/endpoints.rst
#285. More status codes and another endpoint that I forgot to add.
=> (docs) Add reset endpoint and more status codes

.travis.yml, application/src/main/java/com/sanctionco/thunder/ThunderModule.java, application/src/main/java/com/sanctionco/thunder/crypto/PasswordHashConfiguration.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/java/com/sanctionco/thunder/validation/RequestValidator.java, application/src/test/java/com/sanctionco/thunder/ThunderConfigurationTest.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, application/src/test/java/com/sanctionco/thunder/validation/RequestValidatorTest.java, docs/manual/configuration-options.rst, scripts/tests/disabled-password-header/config.yaml, scripts/tests/disabled-password-header/docker-compose.yml, scripts/tests/disabled-password-header/tests.yaml
Closes #258.
- Adds a `headerCheck` configuration option to allow for enabling/disabling the password header requirement.
=> Feature: Disable Password Header Check

README.md, docs/index.rst, docs/manual/features.rst
Closes #285.
Adds a `Features` page to the documentation.
=> Add features documentation

README.md, application/pom.xml, application/src/main/java/com/sanctionco/thunder/ThunderApplication.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/resources/success.html, application/src/test/java/com/sanctionco/thunder/email/EmailModuleTest.java, docs/manual/endpoints.rst, docs/manual/features.rst, pom.xml, scripts/tests/general/tests.yaml
Part of #266. I'm still going to add some configuration options for this but I'll do that in a separate PR since it'll be more code.
=> OpenAPI (Swagger) Integration

.travis.yml, Dockerfile, pom.xml
#112
None
NOTE: I am testing Java 10 upgrade first, then I will update this PR to upgrade to Java 11. Hold off on reviewing until then.
Additional note: We should consider enabling support of older Java versions in the client library.
- https://github.com/dropwizard/dropwizard/issues/2318
- https://github.com/FasterXML/jackson-modules-base/issues/37
=> Upgrade to Java 11

application/src/main/java/com/sanctionco/thunder/ThunderModule.java, application/src/main/java/com/sanctionco/thunder/crypto/BCryptHashService.java, application/src/main/java/com/sanctionco/thunder/crypto/HashAlgorithm.java, application/src/main/java/com/sanctionco/thunder/crypto/HashService.java, application/src/main/java/com/sanctionco/thunder/crypto/MD5HashService.java, application/src/main/java/com/sanctionco/thunder/crypto/PasswordHashConfiguration.java, application/src/main/java/com/sanctionco/thunder/crypto/SimpleHashService.java, application/src/test/java/com/sanctionco/thunder/ThunderConfigurationTest.java, application/src/test/java/com/sanctionco/thunder/crypto/BCryptHashServiceTest.java, application/src/test/java/com/sanctionco/thunder/crypto/HashAlgorithmTest.java, application/src/test/java/com/sanctionco/thunder/crypto/MD5HashServiceTest.java, application/src/test/java/com/sanctionco/thunder/crypto/SimpleHashServiceTest.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, config/test-config.yaml, docs/manual/configuration-options.rst, scripts/tests/bcrypt/config.yaml, scripts/tests/bcrypt/tests.yaml, scripts/tests/general/config.yaml, scripts/tests/general/tests.yaml, scripts/tools/integration-tests.sh
Closes #571.
Allows option for common password mistakes to still be accepted as a valid password.
=> Allow common password mistakes

.travis.yml, application/pom.xml, application/src/main/java/com/sanctionco/thunder/dao/UsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoFactory.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbHealthCheck.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoFactory.java, application/src/main/resources/META-INF/services/com.sanctionco.thunder.dao.UsersDaoFactory, application/src/test/java/com/sanctionco/thunder/dao/UsersDaoFactoryTest.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbHealthCheckTest.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoFactoryTest.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoTest.java, application/src/test/resources/fixtures/configuration/dao/mongodb-config.yaml, config/local-dev-config.yaml, docs/index.rst, docs/manual/configuration-options.rst, docs/manual/features.rst, pom.xml, scripts/ci/docker-integration-tests.sh, scripts/tests/mongodb/config.yaml, scripts/tests/mongodb/docker-compose.yml, scripts/tests/mongodb/tests.yaml, scripts/tests/test-runner.js
Closes #572 and fixes #766.
Implementation of UsersDao for MongoDB!
=> New Database Provider: MongoDB

application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbHealthCheck.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbHealthCheck.java, application/src/main/java/com/sanctionco/thunder/email/ses/SesHealthCheck.java, application/src/test/java/com/sanctionco/thunder/email/ses/SesHealthCheckTest.java, scripts/lib/response-handler.js, scripts/tests/general/tests.yaml, scripts/tests/mongodb/tests.yaml, scripts/tests/test-runner.js
=> Test healthcheck in integration tests

application/pom.xml, application/src/main/java/com/sanctionco/thunder/crypto/BCryptHashService.java, application/src/main/java/com/sanctionco/thunder/crypto/HashService.java, application/src/main/java/com/sanctionco/thunder/crypto/MD5HashService.java, application/src/test/java/com/sanctionco/thunder/crypto/MD5HashServiceTest.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, pom.xml, scripts/tests/md5/tests.yaml
=> Add salting to MD5 hash

application/src/main/java/com/sanctionco/thunder/ThunderConfiguration.java, application/src/main/java/com/sanctionco/thunder/email/EmailServiceFactory.java, application/src/main/java/com/sanctionco/thunder/email/disabled/DisabledEmailServiceFactory.java, application/src/main/java/com/sanctionco/thunder/email/ses/SesEmailServiceFactory.java, application/src/main/resources/META-INF/services/com.sanctionco.thunder.email.EmailServiceFactory, application/src/test/java/com/sanctionco/thunder/ThunderConfigurationTest.java, application/src/test/java/com/sanctionco/thunder/email/EmailHealthCheckTest.java, application/src/test/java/com/sanctionco/thunder/email/EmailServiceFactoryTest.java, application/src/test/java/com/sanctionco/thunder/email/EmailServiceTest.java, application/src/test/java/com/sanctionco/thunder/email/disabled/DisabledEmailServiceFactoryTest.java, application/src/test/java/com/sanctionco/thunder/email/ses/SesEmailServiceFactoryTest.java, application/src/test/java/com/sanctionco/thunder/email/ses/SesHealthCheckTest.java, application/src/test/resources/fixtures/configuration/email/disabled/config.yaml, application/src/test/resources/fixtures/configuration/thunder-config-disabled-email.yaml, application/src/test/resources/fixtures/configuration/thunder-config-null-email.yaml, docs/manual/configuration-options.rst, scripts/tests/disabled-email/config.yaml
=> Default to disabled email configuration

application/src/main/java/com/sanctionco/thunder/authentication/basic/BasicAuthConfiguration.java, application/src/main/java/com/sanctionco/thunder/authentication/basic/BasicAuthenticator.java, application/src/main/java/com/sanctionco/thunder/authentication/basic/Key.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/test/java/com/sanctionco/thunder/authentication/basic/BasicAuthenticatorTest.java
=> Use Principal interface in auth interactions

.github/workflows/ci.yml, .lgtm.yml, Dockerfile, application/src/main/java/com/sanctionco/thunder/ThunderApplication.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/java/com/sanctionco/thunder/validation/PropertyValidator.java, pom.xml
Upgrade to the latest Java version.
=> Upgrade Java version to 16

api/src/main/java/com/sanctionco/thunder/models/User.java, api/src/test/java/com/sanctionco/thunder/models/UserTest.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDao.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoTest.java, docs/manual/endpoints.rst, docs/manual/user-attributes.rst, scripts/deploy/helm/test/go.mod, scripts/deploy/helm/test/go.sum, scripts/tests/bcrypt/tests.yaml, scripts/tests/disabled-email/tests.yaml, scripts/tests/disabled-password-header/tests.yaml, scripts/tests/general/tests.yaml, scripts/tests/mongodb/tests.yaml, scripts/tests/sha256/tests.yaml, scripts/tests/test-runner.js, scripts/tests/update-existing-email/tests.yaml
Closes #580. Create a new user, adding the createdTime and lastUpdateTime in the `Dao` implementations, and return that upon success.
=> Return User creationTime and lastUpdateTime with responses

application/pom.xml, application/src/main/java/com/sanctionco/thunder/ThunderConfiguration.java, application/src/main/java/com/sanctionco/thunder/ThunderModule.java, application/src/main/java/com/sanctionco/thunder/validation/PropertyValidationConfiguration.java, application/src/main/java/com/sanctionco/thunder/validation/PropertyValidator.java, application/src/test/java/com/sanctionco/thunder/ThunderApplicationTest.java, application/src/test/java/com/sanctionco/thunder/ThunderConfigurationTest.java, application/src/test/java/com/sanctionco/thunder/validation/PropertyValidatorTest.java, application/src/test/resources/fixtures/configuration/thunder-config-disabled-email.yaml, application/src/test/resources/fixtures/configuration/thunder-config-null-email.yaml, application/src/test/resources/fixtures/configuration/thunder-config.yaml, config/local-dev-config.yaml, config/test-config.yaml, docs/manual/configuration-options.rst, pom.xml, scripts/deploy/helm/test/configmap_test.go, scripts/deploy/helm/thunder/config.yaml, scripts/tests/disabled-email/config.yaml, scripts/tests/disabled-password-header/config.yaml, scripts/tests/general/config.yaml, scripts/tests/mongodb/config.yaml, scripts/tests/update-existing-email/config.yaml, scripts/tools/integration-tests.sh
=> Add allowSubset and allowSuperset options to property validation

application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbHealthCheck.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoFactory.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbHealthCheckTest.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoFactoryTest.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java, scripts/tests/general/tests.yml
=> Use Async DynamoDB Client

application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDao.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoTest.java
=> Use CompletableFuture within MongoDbUsersDao

application/src/main/java/com/sanctionco/thunder/dao/UsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDao.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/test/java/com/sanctionco/thunder/dao/dynamodb/DynamoDbUsersDaoTest.java, application/src/test/java/com/sanctionco/thunder/dao/mongodb/MongoDbUsersDaoTest.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java
=> Update DAO Interface to be async

application/src/main/java/com/sanctionco/thunder/dao/DatabaseError.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/test/java/com/sanctionco/thunder/ThunderApplicationTest.java, application/src/test/java/com/sanctionco/thunder/dao/DatabaseErrorTest.java, application/src/test/java/com/sanctionco/thunder/dao/DatabaseExceptionTest.java, scripts/tests/general/tests.yml, scripts/tests/mongodb/tests.yml, scripts/tests/update-existing-email/tests.yml
=> Some more chaining

application/src/main/java/com/sanctionco/thunder/ThunderModule.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/java/com/sanctionco/thunder/validation/RequestValidator.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, application/src/test/java/com/sanctionco/thunder/validation/RequestValidatorTest.java
=> Move password header check into RequestValidator

application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/main/java/com/sanctionco/thunder/validation/RequestValidationException.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java, application/src/test/java/com/sanctionco/thunder/validation/RequestValidationExceptionTest.java
=> Combine more futures in VerificationResource

application/src/main/java/com/sanctionco/thunder/openapi/OpenApiConfiguration.java, application/src/main/java/com/sanctionco/thunder/openapi/SwaggerAnnotations.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java
=> Add Meta-Annotations for Swagger

api/src/main/java/com/sanctionco/thunder/models/Email.java, api/src/test/java/com/sanctionco/thunder/models/EmailTest.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java
=> Update POST /users to be fully asynchronous

api/src/test/java/com/sanctionco/thunder/models/EmailTest.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java
=> Make PUT users fully async

application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java, application/src/test/resources/junit-platform.properties, pom.xml, scripts/tests/bad-request/tests.yml
=> Make get and delete fully asynchronous

api/src/main/java/com/sanctionco/thunder/models/Email.java, api/src/test/java/com/sanctionco/thunder/models/EmailTest.java, application/src/main/java/com/sanctionco/thunder/ThunderException.java, application/src/main/java/com/sanctionco/thunder/resources/UserResource.java, application/src/main/java/com/sanctionco/thunder/resources/VerificationResource.java, application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java
=> Make VerificationResource fully async

.github/workflows/ci.yml, .github/workflows/perform-release.yml, CHANGELOG.md, Dockerfile, pom.xml, scripts/ci/docker-integration-tests.sh
=> Upgrade to Java 17

.github/workflows/ci.yml, CHANGELOG.md, application/src/main/java/com/sanctionco/thunder/crypto/ArgonHashService.java, application/src/main/java/com/sanctionco/thunder/crypto/HashAlgorithm.java, application/src/test/java/com/sanctionco/thunder/crypto/ArgonHashServiceTest.java, docs/manual/configuration-options.rst, scripts/tests/argon/config.yaml, scripts/tests/argon/docker-compose.yml, scripts/tests/argon/test.js
=> Add Argon2 password hash option

.github/workflows/ci.yml
=> Upgrade helm and kind versions

.github/workflows/ci.yml, .github/workflows/perform-release.yml, CHANGELOG.md, Dockerfile, pom.xml
=> Upgrade to Java 21
