- application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
- application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
- scripts/tester.py
- scripts/thunder_requests/methods.py
- Basic auth shouldn't be a requirement for users clicking the link in their browser
- Also changed the url format sent to the user to include the http:// protocol definition
> Removed basic auth from email verification endpoint

- README.md
- application/src/main/java/com/sanction/thunder/ThunderApplication.java
- application/src/main/java/com/sanction/thunder/ThunderConfiguration.java
- application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java
- application/src/main/java/com/sanction/thunder/email/EmailModule.java
- application/src/main/java/com/sanction/thunder/email/EmailService.java
- application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
- application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
- application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
- application/src/test/java/com/sanction/thunder/email/EmailServiceTest.java
- application/src/test/resources/fixtures/config.yaml
- config.yaml
- local-config.yaml
- scripts/tester.py
- scripts/thunder_requests/methods.py
- scripts/user_details.json
- Restructure `EmailModule` and `EmailService` slightly in order to take in parameters for `endpoint`, `region`, and `fromAddress`.
- This allows for us to configure the endpoint and region through `config.yaml` so that if they change in the future, we don't have to rebuild. It also means that during integration tests we can use a fake email service, as to not hit the real one.
- This also allows us to easily configure the `FROM` address through the `config.yaml`
- Some cleanup on the `EmailService` unit tests
- **Much** improved Python `tester.py` script that:
- Defines functions for test cases and creates a `test_pipeline` to run through the tests in a specific order
- Attempts to delete the user from the database if a failure occurs at any stage (🎉)
> Use configuration for email endpoint and Python test enhancements

- application/src/main/java/com/sanction/thunder/ThunderApplication.java
- application/src/main/java/com/sanction/thunder/ThunderComponent.java
- application/src/main/java/com/sanction/thunder/ThunderConfiguration.java
- application/src/main/java/com/sanction/thunder/dynamodb/DynamoDbConfiguration.java
- application/src/main/java/com/sanction/thunder/dynamodb/DynamoDbModule.java
- application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
- application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
- application/src/test/resources/fixtures/config.yaml
- config.yaml
- local-config.yaml
With this change, we can specify the Dynamo endpoint and region in the config file. This will allow us to easily run integration tests using DynamoDB Local.
> Add DynamoDbConfiguration with endpoint and region

- pom.xml
Combine #35 and #38 from dependabot since they fail on their own. Dropwizard 1.2.3 requires Jackson 2.9.4 and the places that we are using Jackson, 2.9.4 requires Dropwizard 1.2.3
> Upgrade Dropwizard to 1.2.3 and Jackson to 2.9.4

- application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
- application/src/test/java/com/sanction/thunder/dao/PilotUsersDaoTest.java
- application/src/test/java/com/sanction/thunder/email/EmailServiceTest.java
- application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java
- application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
Addresses #41.
- Replace deprecated `Matchers` with `ArgumentMatchers`
- Replace `anyObject()` with `any(<T> class)`
> Fix Mockito deprecation warnings

- README.md
- api/src/main/java/com/sanction/thunder/models/ResponseType.java
- api/src/test/java/com/sanction/thunder/models/ResponseTypeTest.java
- application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
- application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
- client/src/main/java/com/sanction/thunder/ThunderClient.java
- client/src/test/java/com/sanction/thunder/ThunderClientTest.java
Addresses #28.
- Allow the option of returning HTML when the user email is verified
- Use HTML option when building the email in `sendEmail()`
- Add option to get HTML from the Java client
- Update tests and documentation
Changes to the JavaScript library will come shortly after
> Add option for email verification to respond with HTML

- .gitlab-ci.yml
- api/src/main/java/com/sanction/thunder/models/User.java
- api/src/test/java/com/sanction/thunder/models/UserTest.java
- api/src/test/resources/fixtures/empty_properties_user.json
- api/src/test/resources/fixtures/multiple_properties_user.json
- api/src/test/resources/fixtures/no_properties_user.json
- application/src/main/java/com/sanction/thunder/ThunderConfiguration.java
- application/src/main/java/com/sanction/thunder/dynamodb/DynamoDbConfiguration.java
- application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java
- application/src/test/resources/fixtures/config.yaml
- config/cloud-dev-config.yaml
- config/local-dev-config.yaml
- config/prod-config.yaml
- config/test-config.yaml
3 issues in one!
- Address #144: The Docker image that is built on every commit from master is now tagged as `edge`. See the `.gitlab-ci.yml` to see the change.
- Address #145: The `config.yaml` values that used to have a hyphen (-) now use camel-case, which is Dropwizard convention.
- Address #142: Better UserTest, including verifying serialization/deserialization for a User with no properties, empty properties, and multiple properties.
- Update `User` `equals()` and `hashCode()` to include the `password` and `properties` fields as well.
This is a breaking change with configuration files, FYI.
> Improved UserTests, fix configuration syntax

- README.md
- application/src/main/java/com/sanction/thunder/ThunderConfiguration.java
- application/src/main/java/com/sanction/thunder/ThunderModule.java
- application/src/main/java/com/sanction/thunder/resources/UserResource.java
- application/src/main/java/com/sanction/thunder/validation/PropertyValidationRule.java
- application/src/main/java/com/sanction/thunder/validation/PropertyValidator.java
- application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
- application/src/test/java/com/sanction/thunder/resources/UserResourceTest.java
- application/src/test/java/com/sanction/thunder/validation/PropertyValidationRuleTest.java
- application/src/test/java/com/sanction/thunder/validation/PropertyValidatorTest.java
- application/src/test/resources/fixtures/config.yaml
- config/property-validation-config.yaml
- config/test-config.yaml
- scripts/.eslintrc.yml
- scripts/README.md
- scripts/aws/dynamo-table.yaml
- scripts/kubernetes/thunder-config.yaml
- scripts/kubernetes/thunder-deployment.yaml
- scripts/resources/user_details.json
- scripts/src/aws-client.js
- scripts/src/run-thunder-command.js
- scripts/src/test-runner.js
- scripts/tools/bootstrap.sh
- scripts/tools/integration-tests.sh
- scripts/tools/run-local-dependencies.js
Addresses most of #143.
- User properties are validated on `POST` and `PUT`! 🎉
- Property validation is optional. Turn it on by specifying the `properties` section in the `config.yaml`. The absence of a `properties` section means no property validation will be done.
- Currently supports `string`, `integer`, `double`, `boolean`, `list`, and `map`. If I'm missing any common JSON objects let me know.
- Unit tests for new code.
The new config section should look like:
```yaml
properties:
- name: uniqueID
type: string
- name: myProperty
type: list
```
> User Property Validation

- application/src/main/java/com/sanction/thunder/email/EmailModule.java
- application/src/main/resources/success.html
- application/src/main/resources/verification.html
- application/src/main/resources/verification.txt
- application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
- Adds unit tests for `EmailModule` to verify custom and default HTML.
- Fixes bug in `provideSuccessHtml()` (missing `return` statement)
> Add EmailModule Unit Tests and Fix Bug

- application/src/test/resources/logback-test.xml
Don't log anymore during unit tests. This is pretty much unnecessary. It clutters up the `mvn test` output so we can't easily see which tests were run/ the pass and fail numbers. If you need it on for some debugging reasons, simply change this:
```xml
<root level="OFF">
```
to this:
```xml
<root level="INFO">
```
> Supress logging in application unit tests

- application/src/main/java/com/sanction/thunder/email/EmailConfiguration.java
- application/src/main/java/com/sanction/thunder/email/EmailModule.java
- application/src/main/java/com/sanction/thunder/email/MessageOptions.java
- application/src/main/java/com/sanction/thunder/email/MessageOptionsConfiguration.java
- application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
- application/src/main/java/com/sanction/thunder/util/EmailUtilities.java
- application/src/test/java/com/sanction/thunder/ThunderApplicationTest.java
- application/src/test/java/com/sanction/thunder/ThunderConfigurationTest.java
- application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
- application/src/test/java/com/sanction/thunder/email/MessageOptionsConfigurationTest.java
- application/src/test/java/com/sanction/thunder/email/MessageOptionsTest.java
- application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
- application/src/test/java/com/sanction/thunder/util/EmailUtilitiesTest.java
- application/src/test/resources/fixtures/config.yaml
- application/src/test/resources/fixtures/message-options-config.yaml
- config/cloud-dev-config.yaml
- config/local-dev-config.yaml
- config/prod-config.yaml
- config/test-config.yaml
#162.
- More email configuration options (Subject and placeholder string)
- Users can customize the subject of the email message. Defaults to `Account Verification`
- Users can customize the placeholder string in their text files. Defaults to `CODEGEN-URL`
- All email optional configuration is now contained in the `MessageOptionsConfiguration` class
- `VerificationResource` uses a `MessageOptions` object to hold all message options
- Updated tests accordingly
Still to do:
> Enable more Email Configuration Options

- application/src/main/java/com/sanction/thunder/email/EmailModule.java
- application/src/main/java/com/sanction/thunder/email/MessageOptions.java
- application/src/main/java/com/sanction/thunder/email/MessageOptionsConfiguration.java
- application/src/main/java/com/sanction/thunder/resources/VerificationResource.java
- application/src/test/java/com/sanction/thunder/email/EmailModuleTest.java
- application/src/test/java/com/sanction/thunder/email/MessageOptionsTest.java
- application/src/test/java/com/sanction/thunder/resources/VerificationResourceTest.java
Fully resolves #162.
Handle edge cases where:
1. User specifies a custom placeholder but no custom body files: Use the default placeholder
2. User specifies a custom placeholder with only one custom body file: Use the custom placeholder for the custom file, use the default placeholder for the default file
> Handle URL Placeholder Edge Cases

- application/src/main/java/com/sanctionco/thunder/resources/UserResource.java
Closes #238.
Before, if updating a user's email address and there was already a user with the new email address in the database, the CONFLICT error message would be incorrect. This fixes that.
For example:
1. Insert user `firstuser@gmail.com`
2. Insert user `seconduser@gmail.com`
3. Update the first user's email address to `seconduser@gmail.com`
BEFORE the bug fix, the response message would be:
```
User firstuser@simulator.amazonses.com already exists in the database.
```
This doesn't make sense because `firstuser@gmail.com` is the one that is getting their email changed. We want it to say that the new email already exists.
After the bug fix:
```
User seconduser@simulator.amazonses.com already exists in the database.
```
Better!
None
> Fix bug with incorrect response message

- README.md
- pom.xml
This plugin is necessary to release to the Nexus Staging Repo (Maven Central). This was missing, which is why performing the v2.0 release didn't deploy to central. I've gone ahead and deployed v2.0 to central manually. From now on, it should deploy when doing a release.
Closes #140 by adding Maven Central and Javadoc badges to the README
None
> Add Nexus Staging Plugin

- application/src/main/java/com/sanctionco/thunder/crypto/MD5HashService.java
- application/src/main/java/com/sanctionco/thunder/resources/UserResource.java
- application/src/main/java/com/sanctionco/thunder/util/EmailUtilities.java
- application/src/main/java/com/sanctionco/thunder/util/HashUtilities.java
- application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java
- application/src/test/java/com/sanctionco/thunder/util/HashUtilitiesTest.java
- scripts/tests/disabled-email/tests.yaml
- scripts/tests/general/tests.yaml
Fixes #268.
- When updating a user, don't allow the update to overwrite the verification status. Either keep the existing verification status, or if it is a new email, reset the verification status.
- This PR also moves the MD5 hash function into a static method in `HashUtilities` in order to allow for easier unit testing.
There aren't any relevant docs for this right now but I will add some docs about this behavior later.
Also, I will open an issue to add an endpoint that allows for resetting a user's verification status.
> Disallow Verification Status Changes on Update

- application/src/main/java/com/sanctionco/thunder/ThunderModule.java
- application/src/main/java/com/sanctionco/thunder/crypto/BCryptHashService.java
- application/src/main/java/com/sanctionco/thunder/crypto/HashAlgorithm.java
- application/src/main/java/com/sanctionco/thunder/crypto/HashService.java
- application/src/main/java/com/sanctionco/thunder/crypto/MD5HashService.java
- application/src/main/java/com/sanctionco/thunder/crypto/PasswordHashConfiguration.java
- application/src/main/java/com/sanctionco/thunder/crypto/SimpleHashService.java
- application/src/main/java/com/sanctionco/thunder/resources/UserResource.java
- application/src/test/java/com/sanctionco/thunder/ThunderConfigurationTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/BCryptHashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/HashAlgorithmTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/MD5HashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/SimpleHashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/resources/UserResourceTest.java
- application/src/test/java/com/sanctionco/thunder/resources/VerificationResourceTest.java
- docs/manual/configuration-options.rst
- docs/manual/user-attributes.rst
- scripts/tests/bcrypt/config.yaml
- scripts/tests/bcrypt/tests.yaml
- scripts/tests/md5/config.yaml
- scripts/tests/md5/tests.yaml
- scripts/tests/test-runner.js
#258.
- Adds a new configuration option to enable server-side hashing. This option is disabled by default to maintain backwards compatibility. (We will likely switch this to enabled by default in v3.0).
- When enabled, performs password hashing based on the defined algorithm when a user is created or when a user's password is updated.
> Feature: Server Side Hashing

- .travis.yml
Should decrease the time taken to run the integration tests on Travis by not building the client library on each integration test run.
Also remove `sudo: required` as it is now the default.
> Faster integration tests on Travis

- .travis.yml
The Travis builds are now failing for oraclejdk8, possibly due to licensing changes. This changes it to openjdk8.
> Switch to openjdk8 in Travis

- application/pom.xml
- application/src/main/java/com/sanctionco/thunder/openapi/OpenApiConfiguration.java
- application/src/main/resources/version.txt
- application/src/test/java/com/sanctionco/thunder/openapi/OpenApiConfigurationTest.java
Closes #895. Uses Maven's resource filtering feature to replace the `version.txt` file contents with the current version of the project. We then read the `version.txt` file within the `OpenApiConfiguration` java class in order to have the correct version in the swagger resource.
> Populate Swagger version number during build

- .github/workflows/ci.yml
- CHANGELOG.md
- application/pom.xml
- application/src/main/java/com/sanctionco/thunder/crypto/BCryptHashService.java
- application/src/main/java/com/sanctionco/thunder/crypto/Sha256HashService.java
- application/src/test/java/com/sanctionco/thunder/crypto/BCryptHashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/HashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/Sha256HashServiceTest.java
- application/src/test/java/com/sanctionco/thunder/crypto/SimpleHashServiceTest.java
- pom.xml
Replace internal bcrypt hash implementation with `Password4j`. This is more maintained and also includes other algorithms we can use.
> Replace internal bcrypt hash implementation
